# - name: Generate configuration files
#   ansible.builtin.template:
#     src: router.j2
#     dest: "/home/azeez/ansible_eveng_lab/config/{{ inventory_hostname }}.cfg"
#   # loop: "{{routers}}"
---
- name: Generate hostname config
  template:
    src: base_config.j2
    dest: "/home/azeez/ansible_eveng_lab/config/{{ inventory_hostname }}_hostname.cfg"

- name: Generate management interface config
  template:
    src: mgmt_config.j2
    dest: "/home/azeez/ansible_eveng_lab/config/{{ inventory_hostname }}_mgmt.cfg"

- name: Generate interface config
  template:
    src: interface_config.j2
    dest: "/home/azeez/ansible_eveng_lab/config/{{ inventory_hostname }}_interfaces.cfg"

- name: Generate VLAN config
  template:
    src: vlan_config.j2
    dest: "/home/azeez/ansible_eveng_lab/config/{{ inventory_hostname }}_vlans.cfg"

- name: Generate BGP config
  template:
    src: bgp_config.j2
    dest: "/home/azeez/ansible_eveng_lab/config/{{ inventory_hostname }}_bgp.cfg"

- name: Generate NTP config
  template:
    src: ntp_config.j2
    dest: "/home/azeez/ansible_eveng_lab/config/{{ inventory_hostname }}_ntp.cfg"

- name: Generate configuration files locally
  ansible.builtin.template:
    src: full_config.j2
    dest: "/home/azeez/ansible_eveng_lab/config/{{ inventory_hostname }}.cfg"
  delegate_to: localhost
