# ---
# routers:
#   - hostname: R1
#     enable_secret: Eveng138343
#     loopback: 1.1.1.1 255.255.255.255

#   - hostname: R2
#     enable_secret: Eveng138343
#     loopback: 2.2.2.2 255.255.255.255

#   - hostname: R3
#     enable_secret: Eveng138343
#     loopback: 3.3.3.3 255.255.255.255

    
