---
routers:
  - hostname: leaf01
    ansible_host: 192.168.91.101
    ansible_user: admin
    ansible_password: Eveng138343
    ansible_network_os: arista.eos.eos

  - hostname: leaf02
    ansible_host: 192.168.91.102
    ansible_user: admin
    ansible_password: Eveng138343
    ansible_network_os: arista.eos.eos

  - hostname: spine1
    ansible_host: 192.168.91.11
    ansible_user: admin
    ansible_password: Eveng138343
    ansible_network_os: arista.eos.eos

vlans:
  - id: 10
    name: "VLAN10"
  - id: 20
    name: "VLAN20"

interfaces:
  leaf01:
    - name: "Ethernet2"
      vlan: 10
  leaf02:
    - name: "Ethernet2"
      vlan: 20
  spine1: []

management_interfaces:
  leaf01:
    - name: "Management1"
      ipv4:
        - "192.168.91.101/24"
  leaf02:
    - name: "Management1"
      ipv4:
        - "192.168.91.102/24"
  spine1:
    - name: "Management1"
      ipv4:
        - "192.168.91.11/24"

bgp_peers:
  spine1:
    asn: 65000
    router_id: "11.11.11.11"
    neighbors:
      - neighbor_address: "192.168.91.101"
        remote_as: 65001
      - neighbor_address: "192.168.91.102"
        remote_as: 65002

  leaf01:
    asn: 65001
    router_id: "101.101.101.101"
    neighbors:
      - neighbor_address: "192.168.91.11"
        remote_as: 65000

  leaf02:
    asn: 65002
    router_id: "102.102.102.102"
    neighbors:
      - neighbor_address: "192.168.91.11"
        remote_as: 65000
# admin_password: "Eveng138343"
ntp_server: "8.8.8.8"
admin_password: "Eveng138343"